name = "hydrogen-energy-slides"
main = "dist/index.html"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
dir = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200